version: "3.9"
services:
  postgres:
    image: postgres:15.4
    environment:
      POSTGRES_DB: "course_analytics"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "mypassword"
    ports:
      - "5432:5432"